### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by weriomat** [42willow/wallpapers#3]
I would like to use your wallpapers and I would like for there to be a license.
There are numerous resources such as [choosealicense.com](https://choosealicense.com/) to help choose a license.

Thanks!

**Comment by 42willow** [comment]
Hi, I've added the unlicense since this is kind of just a repo with other people's art in it...

I'll get around to adding proper credit for the individual artists at some point too https://github.com/42Willow/wallpapers/issues/4
